### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by yqrashawn** [halfwit/dotfiles#1]
Got no idea. Just switching to linux.

**Comment by halfwit** [comment]
Well, manpages are mostly just collections of personal settings (in general). I've been considering breaking out the dsearch + plumber bits to seperate repos, so that  whomever could package it for themselves if they wanted. If you want to know how to do a specific thing, let me know.

**Comment by leothelocust** [comment]
@halfwit I would really like to know how to get started using this too.

I've downloaded your dotfiles into a `dev` dir and have started sifting through it.  I've been able to run `./share/dsearch/yt [search param]` however, i'm struggling to get much beyond that.  For example, `./share/dsearch/yt \!pl interstellar`would conceivably return a list of "playlists" that I can choose, but instead it returns a completely unrelated list of videos.

I'm sure I'm just doing something wrong, but would really love to have all these great "search" menus.

Also, I'm using i3 and would like to `bindsym Mod1+space` to this, but cannot figure out where the "starting" point is.  (i.e. which file in the repo is the one I can call from command line and type the `!` comands?)

Thanks in advance!

**Comment by halfwit** [comment]
The command that handles the firing off of the !yt and such is bin/dsearch, so firing off the !pl

**Comment by halfwit** [comment]
But I should start work on wrapping this up as a standalone solution soon, that may make things a bit more friendly to use

**Comment by leothelocust** [comment]
yeah, i thought that was it, and I modified the vars to match my system, but I get the following error

```
lsgrp: lsgrp: can't read group database: Invalid argument: Invalid argument
./dsearch: line 19: cd: /home/locust/Projects/devel/halfwit/share/bookmark: No such file or directory
```

I'm not sure what `line 19` is suppose to point to.  But regardless the `lsgrp` command doesn't seem to like me either :(

**Comment by halfwit** [comment]
Yeah, lsgrp is from the wmgroup repository, I use it to list open browser windows. Would be perfectly safe to remove those lines fully, for your needs.

**Comment by leothelocust** [comment]
Cool.

So for some documenting purposes, I'm documenting my steps to get this working.

**Comment by halfwit** [comment]
Heh, nice.

**Comment by halfwit** [comment]
I had started work on breaking out certain notable aspects in to their own repositories, and it seems it should be possible to do so. At some point in the near-ish future, it will be simple as running a make install, and setting configuration options.

**Comment by halfwit** [comment]
So as of now, standalone utilities have been broken out into seperate repositories; that can be installed and configured on their own.

**Comment by leothelocust** [comment]
Awesome!
