### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by anarcat** [halfwit/dotfiles#11]
links to dsearch and handlers are broken in the readme, missing branch?

**Comment by halfwit** [comment]
Thank you! I'll update that.

**Comment by anarcat** [comment]
sorry about this, but there's still a broken link: plumber goes to https://github.com/halfwit/dotfiles/blob/main/bin/plumber which is a 404 as well... i'm also wondering what the state of [dsearch](https://github.com/halfwit/dsearch) is considering it's marked as "archived"... is plumber the replacement? would be nice to have information in the dsearch repo about such fate...

**Comment by halfwit** [comment]
Basically, I moved to using the plan9 plumber for all of this stuff, the plumber there does what I want and has a bit cleaner interactions. So for search, I issue a plumb command with like, `-d search` and match in the plumber rules, in a few weeks I'll update my dotfiles to  include those plumber config files.
