### ISSUE TITLE
This is all bullshit

### ISSUE THREAD

**Issue by ghost** [halfwit/dotfiles#2]
Where are you goddamnit.

**Comment by halfwit** [comment]
Damnit, lol

**Comment by halfwit** [comment]
I blame fro, he's just so curmudgeonly for an old rap enthusiast.

**Comment by alyptik** [comment]
FOR CHRISTS SAKE STOP EATING ALL MY CEREAL

**Comment by alyptik** [comment]
@acannibalox AND YOU. YOU. PUT THE TOILET SEAT DOWN DAMMIT

**Comment by acannibalox** [comment]
@alyptik I dont use toilets. I use cornfields. Brier patches. Thickets. Things of that nature.

**Comment by halfwit** [comment]
Nature calls, nature answers. It's the natural order.

**Comment by halfwit** [comment]
I believe this issue has been solved, marking as closed.
