### ISSUE TITLE
[Q] Where to put mpv?

### ISSUE THREAD

**Issue by tuyenpm9** [halfwit/dotfiles#7]
I read `handlers` and some relevant repos and it requires `mpv` under `XDG_DATA_HOME` means fallback to `~/.local/share/` folder by default.

Should I put `mpv` folder in dotfiles under `~/.local/share` or `~/.config/mpv`?

**Comment by halfwit** [comment]
~/.local/share/mpv

**Comment by halfwit** [comment]
as a folder. It simply holds files for menu entries

**Comment by tuyenpm9** [comment]
Thanks.
