### ISSUE TITLE
[Q] Cloudef/dmenu-pango-imlib too old

### ISSUE THREAD

**Issue by tuyenpm9** [halfwit/dotfiles#8]
Does current upstream from suckless support for submenu similar to this one?

**Comment by tuyenpm9** [comment]
I think follow upstream and do necessary patches are better, maybe you need images in dmenu.

Have to try this submenu in current upstream one, any suggestions how it would be?

**Comment by halfwit** [comment]
No. ytcli will have to be called without the image flag, and things like !doc and !is from dsearch may not behave

**Comment by tuyenpm9** [comment]
I still can only get `!song` to work, others still in mystery, but hey quick track down to favor song and play it is good.

I'll track down handlers later, and possible raise many questions, thanks for your time.
